# Generated by Django 2.2.5 on 2019-09-19 11:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[core.models.validate_birth_date], verbose_name='Date of Birth'),
        ),
    ]
